name: Generate profile summary cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ruancsv
          BRANCH_NAME: main
          UTC_OFFSET: -3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
